import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  const session = useSession();

  console.log(session);
  const imageUser = session.data?.user.image;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col items-center justify-center gap-3">
        <h1>HOME PAGE</h1>
        {session.status === "unauthenticated" ? (
          <button onClick={() => signIn()}>Sign In</button>
        ) : (
          <button onClick={() => signOut()}>Sign Out</button>
        )}
        <p>{session.data?.user.name}</p>
        <p>{session.data?.user.email}</p>
        <p>{session.data?.user.role}</p>
        <Image
          src={imageUser ?? ""}
          width={50}
          height={50}
          alt="Picture of the author"
        />
      </div>
    </>
  );
}
